#!/bin/bash
if [ ! -d ".git" ]; then
    echo "We have detected that you have downloaded pAste-master.zip from the GitHub website. This is the WRONG way to download pAste. Please download pAste with the command 'git clone --recursive https://github.com/exp111/pAste.git'"
    exit
else
	git pull
	git submodule update --recursive --remote
	git pull --recurse-submodules
	./build
fi
